import clsx from 'clsx'
import type { Metadata } from 'next'

import { nekst } from '@/assets/fonts'
import '@/assets/styles/globals.css'

import Background from '@/layout/background/Background'

export const metadata: Metadata = {
  title: 'Orap form',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={clsx(nekst.variable, 'antialiased')}>
        <Background />
        {children}
      </body>
    </html>
  )
}
